server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/  # URL, по которому Eureka Client будет обращаться к Eureka Server.

logging:
  level:
    root: INFO
    org:
      springframework: INFO
      springframework.security: DEBUG
      springframework.data.redis.cache: DEBUG
      springframework.security.oauth2: debug
    com.netflix.discovery.DiscoveryClient: OFF
    com.netflix.discovery.InstanceInfoReplicator: OFF
    com.netflix.discovery.shared.transport.decorator: OFF
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%t] %-5level %logger{36} - %msg%n"
    com:
      netflix:
        eureka: off
        discovery: off
    io.opentelemetry: info
    io.micrometer.tracing: info
  file:
    name: logs/sales-point.log

# Jaeger
management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
tracing:
  url: http://localhost:4317

spring:
  application:
    name: sales-point
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        physical_naming_strategy=org:
          hibernate:
            boot:
              model:
                naming:
                  CamelCaseToUnderscoresNamingStrategy:
  liquibase:
    change-log: classpath:/db/changelog/master.yaml
    enabled: true
# Redis
  cache:
    type: redis
  data:
    redis:
      port: 6379
      host: localhost
      lifetime: 10m
# Keycloak
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/edme-realm
